###
GET  http://localhost:3000/api/v1/products

###
GET  http://localhost:3000/api/v1/products/31dc384c-82fc-4751-9652-8d8819247f40


POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "name": "new name",
    "price": 200,
    "image": ""
}

###
PATCH http://localhost:3000/api/v1/products/1
Content-Type: application/json

{
    "name": "new name",
    "price": 200
}

###
DELETE  http://localhost:3000/api/v1/products/1
