
GET  http://localhost:3000/api/v1/products

###
GET  http://localhost:3000/api/v1/products/a01d4b10-aed8-4fb1-bdf3-de9193756512

###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "name": "Name",
    "price": 150,
    "image": "http://placeimg.com/640/480"
}

###
PATCH http://localhost:3000/api/v1/products/a01d4b10-aed8-4fb1-bdf3-de9193756512
Content-Type: application/json

{
    "name": 20,
    "price": "hh"
}

###
DELETE  http://localhost:3000/api/v1/products/a01d4b10-aed8-4fb1-bdf3-de9193756512
