POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
    "name": "new name",
    "price": 200,
    "image": ""
}

###
PATCH http://localhost:3000/api/v1/products/1
Content-Type: application/json

{
    "name": "new name",
    "price": 200
}

###
DELETE  http://localhost:3000/api/v1/products/1

###
GET  http://localhost:3000/api/v1/products/101
